/*
Even Fibonacci numbers

Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class P002_evenFibonacci {
    public static int sum_of_even_fibonacci(int limit) {
        int a = 1;
        int b = 2;
        int fib = b;
        int result = 2;
        while (fib<limit) {
            if (fib%2 == 0) {
                result = result+b;
            }
            fib = a+b;
            a = b;
            b = fib;
        }
        return result;
    }
    public static void main(String[] args) {
        int limit = 4000000;
        int result = sum_of_even_fibonacci(limit);
        System.out.println("The limit is " + limit);
        System.out.println("Sum of even fibinacci: " + result);
    }
}

/*
The limit is 4000000
Sum of even fibinacci: 4613734
*/